project:
  type: website
  output-dir: site  

website:
  title: "Project Miner Lord Design Docs"
  site-url: "https://suwonnuclearfist.github.io/Project-Miner-Lord/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: DSMAS/index.qmd
        text: DSMAS
      - href: Politics/index.qmd
        text: Politics

format:
  html:
    toc: true
    theme: cosmo